arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: meeting_details_localizations.dart
output-class: MeetingDetailsLocalizations
synthetic-package: false
nullable-getter: false