name: meeting_details
publish_to: none
environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  function_and_extension_library:
    path: ../../function_and_extension_library
  meeting_repository:
    path: ../../meeting_repository
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_lints: ^4.0.0

