arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: change_password_localizations.dart
output-class: ChangePasswordLocalizations
synthetic-package: false
nullable-getter: false