name: growth_in

publish_to: 'none'
version: 2.0.4+7
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.6
  flutter_lints: ^4.0.0
  firebase_core: ^3.3.0
  dio: ^5.3.3

  # Local Packages
  growth_in_api:
    path: packages/growth_in_api
  key_value_storage:
    path: packages/key_value_storage
  user_repository:
    path: packages/user_repository
  request_repository:
    path: packages/request_repository
  company_repository:
    path: packages/company_repository
  meeting_repository:
    path: packages/meeting_repository

  function_and_extension_library:
    path: packages/function_and_extension_library


  tab_container:
    path: packages/features/tab_container
  home:
    path: packages/features/home
  more:
    path: packages/features/more


  # Authentication
  sign_in:
    path: packages/features/sign_in
  verify_otp:
    path: packages/features/verify_otp
  reset_password:
    path: packages/features/reset_password
  send_otp:
    path: packages/features/send_otp

  # Profile
  switch_account_company:
    path: packages/features/switch_account_company
  profile_settings:
    path: packages/features/profile_settings
  profile_info:
    path: packages/features/profile_info
  change_password:
    path: packages/features/change_password
  change_email:
    path: packages/features/change_email
  tickets:
    path: packages/features/tickets
  submit_ticket:
    path: packages/features/submit_ticket
  ticket_messages:
    path: packages/features/ticket_messages


  # Requests
  requests:
    path: packages/features/requests
  request_details:
    path: packages/features/request_details
  request_actions:
    path: packages/features/request_actions
  action:
    path: packages/features/action
  action_comments:
    path: packages/features/action_comments
  request_comments:
    path: packages/features/request_comments


    # Meetings
  meetings:
    path: packages/features/meetings
  search_meetings:
    path: packages/features/search_meetings
  meeting_details:
    path: packages/features/meeting_details
  delete_meeting:
    path: packages/features/delete_meeting

  # Domain Models and Component Library
  domain_models:
    path: packages/domain_models
  component_library:
    path: packages/component_library
  flutter_downloader: ^1.11.8

#
#dependency_overrides:
#  wakelock:
#    git:
#      url: https://github.com/chandrabezzo/wakelock.git # repository
#      ref: main # branch
#      path: wakelock/ # folder


flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Black.ttf
        - asset: fonts/Cairo/Cairo-Bold.ttf
        - asset: fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: fonts/Cairo/Cairo-Light.ttf
        - asset: fonts/Cairo/Cairo-Medium.ttf
        - asset: fonts/Cairo/Cairo-Regular.ttf
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
    - family: Gotham
      fonts:
        - asset: fonts/Gotham/GothamBold.ttf
        - asset: fonts/Gotham/GothamBook.ttf
        - asset: fonts/Gotham/GothamLight.ttf
        - asset: fonts/Gotham/GothamMedium.ttf
        - asset: fonts/Gotham/GothamMedium_1.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/icons/tab_container/