arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: delete_meeting_localizations.dart
output-class: DeleteMeetingLocalizations
synthetic-package: false
nullable-getter: false