arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: profile_settings_localizations.dart
output-class: ProfileSettingsLocalizations
synthetic-package: false
nullable-getter: false