arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: post_details_localizations.dart
output-class: PostDetailsLocalizations
synthetic-package: false
nullable-getter: false