arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: request_comments_localizations.dart
output-class: RequestCommentsLocalizations
synthetic-package: false
nullable-getter: false