name: create_meeting
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter

  component_library:
    path: ../../component_library
  meeting_repository:
    path: ../../meeting_repository
  user_repository:
    path: ../../user_repository
  domain_models:
    path: ../../domain_models
  form_fields:
    path: ../../form_fields
  function_and_extension_library:
    path: ../../function_and_extension_library
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.5
  file_picker: ^8.1.2


dev_dependencies:
  flutter_lints: ^4.0.0
