name: cms_repository
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  growth_in_api:
    path: ../growth_in_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  function_and_extension_library:
    path: ../function_and_extension_library
  request_repository:
    path: ../request_repository

  equatable: ^2.0.5
  intl: ^0.19.0


dev_dependencies:
  flutter_lints: ^4.0.0
