arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: profile_info_localizations.dart
output-class: ProfileInfoLocalizations
synthetic-package: false
nullable-getter: false