arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: change_email_localizations.dart
output-class: ChangeEmailLocalizations
synthetic-package: false
nullable-getter: false