arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: request_details_localizations.dart
output-class: RequestDetailsLocalizations
synthetic-package: false
nullable-getter: false