arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: post_version_details_localizations.dart
output-class: PostVersionDetailsLocalizations
synthetic-package: false
nullable-getter: false