name: post_version_details
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  cms_repository:
    path: ../../cms_repository
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
dev_dependencies:
  flutter_lints: ^4.0.0


