arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: request_actions_localizations.dart
output-class: RequestActionsLocalizations
synthetic-package: false
nullable-getter: false