name: requests
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  request_repository:
    path: ../../request_repository
  percent_indicator: ^4.2.3
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7


