arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: action_comments_localizations.dart
output-class: ActionCommentsLocalizations
synthetic-package: false
nullable-getter: false