arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: file_comments_localizations.dart
output-class: FileCommentsLocalizations
synthetic-package: false
nullable-getter: false