arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: schedule_meeting_localizations.dart
output-class: ScheduleMeetingLocalizations
synthetic-package: false
nullable-getter: false