arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: tab_container_localizations.dart
output-class: TabContainerLocalizations
synthetic-package: false
nullable-getter: false