name: ticket_messages
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  file_picker: ^8.1.2
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  user_repository:
    path: ../../user_repository
  function_and_extension_library:
    path: ../../function_and_extension_library
  image_picker: ^1.1.2


