name: component_library
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  function_and_extension_library:
    path: ../function_and_extension_library
  domain_models:
    path: ../domain_models
  form_fields:
    path: ../form_fields
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  syncfusion_flutter_datepicker: ^25.2.4
  collection: ^1.18.0
  file_picker: ^8.1.3
  dio: ^5.7.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.5
dev_dependencies:
  flutter_lints: ^4.0.0

